import { supabase } from './supabase';
import { classifyReport } from './safety';
import type { ReportInsert, ReportStatus, OperationalPriority } from '@/types';

interface DemoReport {
  ward: string;
  medicine_category: string;
  workflow_stage: string;
  incident_type: string;
  operational_priority: OperationalPriority;
  contributing_factors: string[];
  short_description: string;
  immediate_action: string | null;
  medication_administered: 'Yes' | 'No' | 'Unsure';
  patient_harm_status: 'No' | 'Yes' | 'Unsure';
  anonymous: boolean;
  reporter_identifier: string | null;
  status: ReportStatus;
  reviewer_notes: string | null;
  human_verified_category: string | null;
  days_ago: number;
}

const DEMO_REPORTS: DemoReport[] = [
  {
    ward: 'ICU',
    medicine_category: 'Anticoagulant',
    workflow_stage: 'Administration',
    incident_type: 'Duplicate Order',
    operational_priority: 'HIGH',
    contributing_factors: ['Communication', 'Handover'],
    short_description:
      'A potential duplicate anticoagulant order was identified during checking before administration.',
    immediate_action: 'Administration was paused while the order was reviewed through the existing ward process.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Action Required',
    reviewer_notes: 'Duplicate order confirmed. Escalated to prescriber for clarification.',
    human_verified_category: 'Duplicate Order',
    days_ago: 1,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Insulin',
    workflow_stage: 'Storage',
    incident_type: 'Storage Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Storage Layout'],
    short_description:
      'An insulin product was found in the incorrect designated storage location before medication preparation.',
    immediate_action: 'The insulin was relocated to the correct storage area and staff were informed.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 2,
  },
  {
    ward: 'Emergency',
    medicine_category: 'Opioid',
    workflow_stage: 'Preparation',
    incident_type: 'Wrong Dose',
    operational_priority: 'HIGH',
    contributing_factors: ['Interruption', 'Workload'],
    short_description:
      'During a busy shift with multiple interruptions, a wrong dose of opioid was drawn up before a double-check caught the error.',
    immediate_action: 'The prepared syringe was discarded and a new dose was prepared with a second checker present.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'Interruption identified as key factor. Staff reminded about do-not-disturb during preparation.',
    human_verified_category: 'Wrong Dose',
    days_ago: 5,
  },
  {
    ward: 'Surgical Ward',
    medicine_category: 'Concentrated Electrolyte',
    workflow_stage: 'Dispensing',
    incident_type: 'Wrong Medication',
    operational_priority: 'HIGH',
    contributing_factors: ['Similar Packaging', 'Labelling'],
    short_description:
      'Two concentrated electrolyte vials with similar packaging were stored adjacent to each other. The wrong vial was selected before dispensing was halted by a pharmacist check.',
    immediate_action: 'The incorrect vial was returned to storage. A separator was placed between the two products.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: false,
    reporter_identifier: 'STAFF-042',
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 3,
  },
  {
    ward: 'Paediatrics',
    medicine_category: 'Sedative',
    workflow_stage: 'Prescribing',
    incident_type: 'Wrong Dose',
    operational_priority: 'HIGH',
    contributing_factors: ['Electronic System', 'Training'],
    short_description:
      'The electronic prescribing system defaulted to an adult dose for a paediatric sedative. The error was identified during a weight-based check.',
    immediate_action: 'The order was corrected before any preparation began.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Submitted',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 0,
  },
  {
    ward: 'ICU',
    medicine_category: 'Insulin',
    workflow_stage: 'Administration',
    incident_type: 'Wrong Timing',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Communication', 'Handover'],
    short_description:
      'An insulin sliding scale dose was administered at the wrong time due to a miscommunication during shift handover.',
    immediate_action: 'The timing was documented and the next dose was adjusted per protocol.',
    medication_administered: 'Yes',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'Handover communication improved. Timing checklist introduced.',
    human_verified_category: 'Wrong Timing',
    days_ago: 8,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Anticoagulant',
    workflow_stage: 'Prescribing',
    incident_type: 'Prescribing Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Workload', 'Electronic System'],
    short_description:
      'A prescription for an anticoagulant was entered with the wrong frequency due to a dropdown selection error under high workload.',
    immediate_action: 'The prescriber was contacted and the frequency was corrected.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: false,
    reporter_identifier: 'STAFF-118',
    status: 'Closed',
    reviewer_notes: 'System dropdown usability flagged for review.',
    human_verified_category: 'Prescribing Error',
    days_ago: 10,
  },
  {
    ward: 'Emergency',
    medicine_category: 'Opioid',
    workflow_stage: 'Administration',
    incident_type: 'Wrong Route',
    operational_priority: 'HIGH',
    contributing_factors: ['Interruption', 'Staffing'],
    short_description:
      'An opioid was nearly administered via the wrong route. The label was checked at the bedside and the error was caught.',
    immediate_action: 'Administration was stopped. The correct route was confirmed with a second nurse.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Action Required',
    reviewer_notes: 'Route confirmation protocol reinforced.',
    human_verified_category: 'Wrong Route',
    days_ago: 4,
  },
  {
    ward: 'Surgical Ward',
    medicine_category: 'Chemotherapy',
    workflow_stage: 'Preparation',
    incident_type: 'Labelling Error',
    operational_priority: 'HIGH',
    contributing_factors: ['Labelling', 'Workload'],
    short_description:
      'A chemotherapy infusion bag was mislabelled with the wrong patient name during preparation. The error was found during the final check.',
    immediate_action: 'The bag was relabelled correctly and the preparation area was reviewed.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 6,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Sedative',
    workflow_stage: 'Monitoring',
    incident_type: 'Communication Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Communication', 'Handover'],
    short_description:
      'A sedative infusion rate change was not communicated during handover, leading to a monitoring gap.',
    immediate_action: 'The rate was verified and monitoring was reinstated.',
    medication_administered: 'Yes',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'SBAR handover format reinforced for infusion changes.',
    human_verified_category: 'Communication Error',
    days_ago: 12,
  },
  {
    ward: 'ICU',
    medicine_category: 'Concentrated Electrolyte',
    workflow_stage: 'Storage',
    incident_type: 'Storage Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Storage Layout', 'Environment'],
    short_description:
      'Concentrated potassium chloride was found stored outside the designated restricted area. It was relocated immediately.',
    immediate_action: 'The vials were moved to the restricted storage area and the incident was logged.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: false,
    reporter_identifier: 'STAFF-077',
    status: 'Closed',
    reviewer_notes: 'Storage audit completed. All concentrated electrolytes relocated.',
    human_verified_category: 'Storage Error',
    days_ago: 15,
  },
  {
    ward: 'Paediatrics',
    medicine_category: 'Other High-Risk Medicine',
    workflow_stage: 'Transcription',
    incident_type: 'Wrong Dose',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Workload', 'Training'],
    short_description:
      'A medication order was transcribed with the wrong dose unit (mg instead of ml) for a paediatric patient.',
    immediate_action: 'The transcription was corrected after a double-check by a second staff member.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Submitted',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 1,
  },
  {
    ward: 'Emergency',
    medicine_category: 'Insulin',
    workflow_stage: 'Preparation',
    incident_type: 'Wrong Dose',
    operational_priority: 'HIGH',
    contributing_factors: ['Similar Packaging', 'Interruption'],
    short_description:
      'Two insulin products with similar packaging were stored next to each other. The wrong one was selected before a barcode scan caught the error.',
    immediate_action: 'The correct product was selected. Physical separation was recommended.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 2,
  },
  {
    ward: 'Surgical Ward',
    medicine_category: 'Anticoagulant',
    workflow_stage: 'Administration',
    incident_type: 'Duplicate Order',
    operational_priority: 'HIGH',
    contributing_factors: ['Electronic System', 'Communication'],
    short_description:
      'A duplicate anticoagulant order appeared in the system after a prescriber re-entered it without checking existing orders.',
    immediate_action: 'The duplicate was cancelled before administration.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Action Required',
    reviewer_notes: 'Duplicate order alerting requested from IT.',
    human_verified_category: 'Duplicate Order',
    days_ago: 3,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Opioid',
    workflow_stage: 'Monitoring',
    incident_type: 'Communication Error',
    operational_priority: 'LOW',
    contributing_factors: ['Staffing', 'Environment'],
    short_description:
      'A patient on an opioid infusion was not monitored at the required interval due to staffing pressures on the ward.',
    immediate_action: 'Monitoring was resumed and the incident was reported to the shift lead.',
    medication_administered: 'Yes',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'Staffing levels escalated to management.',
    human_verified_category: 'Communication Error',
    days_ago: 18,
  },
  {
    ward: 'ICU',
    medicine_category: 'Sedative',
    workflow_stage: 'Handover',
    incident_type: 'Communication Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Handover', 'Interruption'],
    short_description:
      'During a handover interrupted by an emergency call, a sedative infusion detail was omitted from the verbal handover.',
    immediate_action: 'The detail was communicated in a follow-up call and documented.',
    medication_administered: 'Yes',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 7,
  },
  {
    ward: 'Emergency',
    medicine_category: 'Chemotherapy',
    workflow_stage: 'Dispensing',
    incident_type: 'Labelling Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Labelling', 'Workload'],
    short_description:
      'A chemotherapy oral tablet was dispensed with an incorrect label indicating the wrong dosing schedule.',
    immediate_action: 'The label was reprinted with the correct schedule before the medication reached the patient.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: false,
    reporter_identifier: 'STAFF-203',
    status: 'Closed',
    reviewer_notes: 'Label printing process reviewed.',
    human_verified_category: 'Labelling Error',
    days_ago: 20,
  },
  {
    ward: 'Paediatrics',
    medicine_category: 'Insulin',
    workflow_stage: 'Administration',
    incident_type: 'Wrong Timing',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Workload', 'Interruption'],
    short_description:
      'An insulin dose was administered 45 minutes late due to competing priorities during a busy medication round.',
    immediate_action: 'The timing was documented and blood glucose was monitored more frequently.',
    medication_administered: 'Yes',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Submitted',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 0,
  },
  {
    ward: 'Surgical Ward',
    medicine_category: 'Concentrated Electrolyte',
    workflow_stage: 'Preparation',
    incident_type: 'Wrong Dose',
    operational_priority: 'HIGH',
    contributing_factors: ['Similar Packaging', 'Storage Layout'],
    short_description:
      'A concentrated electrolyte ampoule was confused with a diluted version due to similar packaging. The error was caught during preparation.',
    immediate_action: 'The correct ampoule was selected. The products were physically separated.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Action Required',
    reviewer_notes: 'Tall-man lettering recommended for labels.',
    human_verified_category: 'Wrong Dose',
    days_ago: 4,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Anticoagulant',
    workflow_stage: 'Administration',
    incident_type: 'Wrong Medication',
    operational_priority: 'HIGH',
    contributing_factors: ['Similar Packaging', 'Labelling'],
    short_description:
      'Two anticoagulant injectable products with similar packaging were confused. The wrong one was brought to the bedside before a barcode check identified the error.',
    immediate_action: 'The correct medication was retrieved. The products were separated in storage.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 5,
  },
  {
    ward: 'ICU',
    medicine_category: 'Opioid',
    workflow_stage: 'Prescribing',
    incident_type: 'Prescribing Error',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Electronic System', 'Training'],
    short_description:
      'An opioid was prescribed via the electronic system with an incorrect rate for a continuous infusion. A pharmacist caught the error during verification.',
    immediate_action: 'The prescription was corrected before any preparation began.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'Prescriber training on infusion rates scheduled.',
    human_verified_category: 'Prescribing Error',
    days_ago: 14,
  },
  {
    ward: 'Emergency',
    medicine_category: 'Sedative',
    workflow_stage: 'Administration',
    incident_type: 'Wrong Route',
    operational_priority: 'HIGH',
    contributing_factors: ['Interruption', 'Workload'],
    short_description:
      'A sedative was nearly given via IV instead of oral route during a high-acuity period. The route was double-checked at the bedside.',
    immediate_action: 'The correct oral formulation was administered instead.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Submitted',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 1,
  },
  {
    ward: 'Surgical Ward',
    medicine_category: 'Insulin',
    workflow_stage: 'Preparation',
    incident_type: 'Wrong Dose',
    operational_priority: 'HIGH',
    contributing_factors: ['Workload', 'Staffing'],
    short_description:
      'An insulin dose was incorrectly drawn up during a short-staffed shift. A second checker identified the discrepancy before administration.',
    immediate_action: 'The dose was reprepared with a witness present.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Under Review',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 2,
  },
  {
    ward: 'Medical Ward',
    medicine_category: 'Other High-Risk Medicine',
    workflow_stage: 'Storage',
    incident_type: 'Storage Error',
    operational_priority: 'LOW',
    contributing_factors: ['Storage Layout'],
    short_description:
      'A high-risk medication was found stored in the general medication area instead of the designated high-risk cupboard.',
    immediate_action: 'The medication was relocated to the correct cupboard.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Closed',
    reviewer_notes: 'Storage layout reviewed.',
    human_verified_category: 'Storage Error',
    days_ago: 25,
  },
  {
    ward: 'Paediatrics',
    medicine_category: 'Anticoagulant',
    workflow_stage: 'Dispensing',
    incident_type: 'Wrong Dose',
    operational_priority: 'MEDIUM',
    contributing_factors: ['Training', 'Electronic System'],
    short_description:
      'A paediatric anticoagulant dose was dispensed at an adult concentration. The error was caught during a weight-based verification.',
    immediate_action: 'The correct paediatric formulation was dispensed.',
    medication_administered: 'No',
    patient_harm_status: 'No',
    anonymous: true,
    reporter_identifier: null,
    status: 'Submitted',
    reviewer_notes: null,
    human_verified_category: null,
    days_ago: 0,
  },
];

export async function loadDemoData(): Promise<{ loaded: number; skipped: boolean }> {
  const { count: existingCount } = await supabase
    .from('near_miss_reports')
    .select('id', { count: 'exact', head: true })
    .eq('is_synthetic', true);

  if ((existingCount || 0) > 0) {
    return { loaded: 0, skipped: true };
  }

  const inserts: ReportInsert[] = DEMO_REPORTS.map((r) => {
    const suggestion = classifyReport(r.short_description);
    const createdDate = new Date();
    createdDate.setDate(createdDate.getDate() - r.days_ago);

    return {
      ward: r.ward,
      medicine_category: r.medicine_category,
      workflow_stage: r.workflow_stage,
      incident_type: r.incident_type,
      operational_priority: r.operational_priority,
      contributing_factors: r.contributing_factors,
      short_description: r.short_description,
      immediate_action: r.immediate_action,
      medication_administered: r.medication_administered,
      patient_harm_status: r.patient_harm_status,
      anonymous: r.anonymous,
      reporter_identifier: r.reporter_identifier,
      status: r.status,
      reviewer_notes: r.reviewer_notes,
      suggested_category: suggestion.suggestedCategory,
      suggestion_confidence: suggestion.confidence,
      human_verified_category: r.human_verified_category,
      is_synthetic: true,
    };
  });

  const { error } = await supabase.from('near_miss_reports').insert(inserts as unknown as Record<string, unknown>[]);

  if (error) {
    throw new Error(`Failed to load demo data: ${error.message}`);
  }

  return { loaded: DEMO_REPORTS.length, skipped: false };
}
